// Auto-generated by semicons
export type IconName = 'lucide:alert-circle' | 'lucide:bell' | 'lucide:calendar' | 'lucide:clock' | 'lucide:error' | 'lucide:home' | 'lucide:info' | 'lucide:mail' | 'lucide:search' | 'lucide:settings' | 'lucide:star' | 'lucide:success' | 'lucide:user' | 'lucide:warning';

export interface IconMeta {
  name: string;
  category?: string | undefined;
  deprecated?: boolean | string | undefined;
  description?: string | undefined;
}

export declare const ICON_META: Record<IconName, IconMeta>;
