// Auto-generated by semicons
export type IconName = 'lucide:alert-circle' | 'lucide:bell' | 'lucide:calendar' | 'lucide:clock' | 'lucide:error' | 'lucide:home' | 'lucide:info' | 'lucide:mail' | 'lucide:search' | 'lucide:settings' | 'lucide:star' | 'lucide:success' | 'lucide:user' | 'lucide:warning';

export interface IconMeta {
  name: string;
  category?: string;
  deprecated?: boolean | string;
  description?: string;
}

export const ICON_META: Record<IconName, IconMeta> = {
  'lucide:alert-circle': {
    name: 'lucide:alert-circle',
    
    
    
  },
  'lucide:bell': {
    name: 'lucide:bell',
    
    
    
  },
  'lucide:calendar': {
    name: 'lucide:calendar',
    
    
    
  },
  'lucide:clock': {
    name: 'lucide:clock',
    
    
    
  },
  'lucide:error': {
    name: 'lucide:error',
    
    
    
  },
  'lucide:home': {
    name: 'lucide:home',
    
    
    
  },
  'lucide:info': {
    name: 'lucide:info',
    
    
    
  },
  'lucide:mail': {
    name: 'lucide:mail',
    
    
    
  },
  'lucide:search': {
    name: 'lucide:search',
    
    
    
  },
  'lucide:settings': {
    name: 'lucide:settings',
    
    
    
  },
  'lucide:star': {
    name: 'lucide:star',
    
    
    
  },
  'lucide:success': {
    name: 'lucide:success',
    
    
    
  },
  'lucide:user': {
    name: 'lucide:user',
    
    
    
  },
  'lucide:warning': {
    name: 'lucide:warning',
    
    
    
  }
};
